### ISSUE TITLE
Acessibility scores

### ISSUE THREAD

**Issue by swagatam101** [carushi/ParasoR#2]
Why are the accessibility scores sometimes greater than one? Isn't this strictly  a probability normalized by the partition function, as defined in http://bioinformatics.oxfordjournals.org/content/27/13/1788.full.pdf+html?

**Comment by carushi** [comment]
Thank you very much for making use of ParasoR.

You are right that accessibility is calculated by ParasoR in the same way described in the paper you have shown.
But ParasoR exhibits the accessibility score in the form of energy (kcal/mol) following the equation
**"-log kT (P) / 1000"** (P is the probability of being accessible)
to show the energetic influence of secondary structure.

If you prefer the accessible probability, you can use **"1 - stem probability"** for 1nt resolution, or there is an option to recompile ParasoR after editing "part_func.hh" file as below.

```
424:    static const bool ene = true;    // output an energy of accessibility;
```
->
```
424:    static const bool ene = false;    // output an energy of accessibility;
```

Then, ParasoR will output raw P values as accessibility.
I am sorry for confusing you, I will add the detail to wiki.

If something is still wrong, please feel free to ask me.
Thanks.
